esphome:
  name: current_sensor
  platform: ESP8266
  board: huzzah





wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

status_led:
  pin: 
    number: GPIO2
    inverted: True

api:

logger:

ota:

sensor:
  - platform: wifi_signal
    name: "Current Sensor WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Current Sensor Uptime"
    update_interval: 60s

  - platform: adc
    pin: A0
    id: adc_sensor

  - platform: ct_clamp
    sensor: adc_sensor
    name: "Measured Current"
    update_interval: 60s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          # Known load: 4.0A
          # Value shown in logs: 0.1333A
          - 0.1333 -> 4.0