esphome:
  name: current_sensor
  platform: ESP8266
  board: huzzah





wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

status_led:
  pin: 
    number: GPIO2
    inverted: True

api:

logger:

ota:

sensor:
  - platform: wifi_signal
    name: "Current Sensor WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Current Sensor Uptime"
    update_interval: 60s

  - platform: adc
    pin: A0
    id: adc_sensor

  - platform: ct_clamp
    sensor: adc_sensor
    name: "Measured Current"
    update_interval: 3s
    filters:
      - calibrate_linear:
        - 0.00131 -> 0.0
        - 0.002   -> 0.17  # LED bulb
        - 0.00278 -> 0.208 # 20W bulb